<%@ taglib uri="/struts-bean"     prefix="b"%>
<%@ taglib uri="/struts-html"     prefix="h"%>
<%@ taglib uri="/struts-logic"    prefix="l"%>
<%@ taglib uri="/struts-tiles"    prefix="t"%>
<%@ taglib uri="/jstl-core"       prefix="c"%>
<%@ taglib uri="/fmt"             prefix="fmt"%>
<%@ taglib uri="/z"               prefix="z"%>
<%@ taglib uri="/string"          prefix="string"%>
<%@ taglib uri="/log"             prefix="log"%>